// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactButton = require("@material/react-button");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(ReactButton.default, {
                  raised: true,
                  children: "meow"
                }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
