// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactTopAppBar = require("@material/react-top-app-bar");
var ReactMaterialIcon = require("@material/react-material-icon");

function App(Props) {
  React.useReducer((function (state, action) {
          if (action) {
            return /* record */[/* drawerOpen */false];
          } else {
            return /* record */[/* drawerOpen */true];
          }
        }), /* record */[/* drawerOpen */true]);
  React.createElement("i", {
        className: "material-icons"
      }, "alarm");
  return React.createElement("div", {
              className: "container"
            }, React.createElement(ReactTopAppBar.default, {
                  fixed: true,
                  children: React.createElement(ReactTopAppBar.TopAppBarRow, {
                        children: React.createElement(ReactTopAppBar.TopAppBarSection, {
                              align: "start",
                              children: null
                            }, React.createElement(ReactTopAppBar.TopAppBarIcon, {
                                  navIcon: true,
                                  children: React.createElement("div", {
                                        onClick: (function (_e) {
                                            console.log("pressed!");
                                            return /* () */0;
                                          })
                                      }, React.createElement(ReactMaterialIcon.default, {
                                            className: "unselectable",
                                            icon: "menu",
                                            hasRipple: true
                                          }))
                                }), React.createElement(ReactTopAppBar.TopAppBarTitle, {
                                  children: "title"
                                }))
                      })
                }), null);
}

var make = App;

exports.make = make;
/* react Not a pure module */
