// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactButton = require("@material/react-button");

function Body(Props) {
  return React.createElement("div", undefined, React.createElement("div", undefined, "body is here"), React.createElement(ReactButton.default, {
                  raised: true,
                  children: "raised"
                }));
}

var make = Body;

exports.make = make;
/* react Not a pure module */
