// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var Icon = /* module */[];

var Button = /* module */[];

exports.Icon = Icon;
exports.Button = Button;
/* No side effect */
